-- Run in lab_db1 and lab_db2 on both clusters as an admin that may SET ROLE
-- lab_owner. Logical replication does not create schemas or tables.
GRANT CONNECT ON DATABASE :"DBNAME" TO lab_app, lab_deployer;
GRANT CREATE ON SCHEMA public TO lab_owner;
CREATE SCHEMA IF NOT EXISTS cutover_control AUTHORIZATION lab_owner;

SET ROLE lab_owner;

CREATE TABLE public.accounts (
    account_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance bigint NOT NULL CHECK (balance >= 0),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE public.transfers (
    transfer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id bigint NOT NULL REFERENCES public.accounts(account_id),
    to_account_id bigint NOT NULL REFERENCES public.accounts(account_id),
    amount integer NOT NULL CHECK (amount > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (from_account_id <> to_account_id)
);

CREATE TABLE public.event_log (
    transfer_id bigint PRIMARY KEY REFERENCES public.transfers(transfer_id),
    event_type text NOT NULL CHECK (event_type = 'transfer.created'),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE cutover_control.replication_probe (
    cutover_test_id uuid PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    marker text NOT NULL
);

COMMENT ON TABLE cutover_control.replication_probe
    IS 'cutover-controller replication probe v1';

RESET ROLE;

GRANT USAGE ON SCHEMA public, cutover_control TO lab_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON
    public.accounts, public.transfers, public.event_log TO lab_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO lab_app;

-- Grant the applicable role on each cluster; ignore the statement for the
-- role that intentionally does not exist there.
-- SOURCE: GRANT USAGE ON SCHEMA public, cutover_control TO lab_forward_repl;
-- SOURCE: GRANT SELECT ON public.accounts, public.transfers, public.event_log,
--         cutover_control.replication_probe TO lab_forward_repl;
-- TARGET: GRANT USAGE ON SCHEMA public, cutover_control TO lab_reverse_repl;
-- TARGET: GRANT SELECT ON public.accounts, public.transfers, public.event_log,
--         cutover_control.replication_probe TO lab_reverse_repl;
